spring:
  application:
    name: HaiYanFlowers
  jackson:
    serialization:
      write-dates-as-timestamps: true
  main:
    allow-bean-definition-overriding: true
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  1000MB
      # 设置总上传的文件大小
      max-request-size:  2000MB
  datasource:
    url: jdbc:mysql://localhost:3306/salted_fish?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9001
#在线文档配置
deflower-swagger:
  enable: true
  api-info:
    title: 采花
    description: 采花API
    version: 1.0.0
#日志
logging:
  level:
    com.haiyan.deflower: debug
    org.springframework: warn
#操作数据库的设置
mybatis:
  mapper-locations: classpath:mapper/*.xml
# 项目相关配置
ruoyi:
  # 名称
  name: deflower
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: E:/GitWarehouse/salted-fish/uploadPath
